# This is a basic workflow to help you get started with Actions

name: CI

on:
  #schedule:
  #- cron: "0 15 * * 1-4"

  workflow_dispatch:


jobs:
  build:
    # env: 
    #   HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release Candidate
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        # with:
        #   #body_path: ${{ github.workspace }}-CHANGELOG.txt
        #   body: test release process
        #   draft: true
        #   prerelease: true
        #   #repository: # optional
        #   generate_release_notes: true
      # get output for git ref
      # - name: Login to Heroku
      #   run: heroku login 
      # - name: Push to Heroku Remote
      #   run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/trada-dev1.git origin/master:master

        
